import { qKeys } from './keys';

const DOM_CODE_TO_UIOHOOK = new Map<string, number>([
  ['Backspace', qKeys.Backspace],
  ['Tab', qKeys.Tab],
  ['Enter', qKeys.Enter],
  ['CapsLock', qKeys.CapsLock],
  ['Escape', qKeys.Escape],
  ['Space', qKeys.Space],
  ['PageUp', qKeys.PageUp],
  ['PageDown', qKeys.PageDown],
  ['End', qKeys.End],
  ['Home', qKeys.Home],
  ['ArrowLeft', qKeys.ArrowLeft],
  ['ArrowUp', qKeys.ArrowUp],
  ['ArrowRight', qKeys.ArrowRight],
  ['ArrowDown', qKeys.ArrowDown],
  ['Insert', qKeys.Insert],
  ['Delete', qKeys.Delete],
  ['Digit0', qKeys[0]],
  ['Digit1', qKeys[1]],
  ['Digit2', qKeys[2]],
  ['Digit3', qKeys[3]],
  ['Digit4', qKeys[4]],
  ['Digit5', qKeys[5]],
  ['Digit6', qKeys[6]],
  ['Digit7', qKeys[7]],
  ['Digit8', qKeys[8]],
  ['Digit9', qKeys[9]],
  ['KeyA', qKeys.A],
  ['KeyB', qKeys.B],
  ['KeyC', qKeys.C],
  ['KeyD', qKeys.D],
  ['KeyE', qKeys.E],
  ['KeyF', qKeys.F],
  ['KeyG', qKeys.G],
  ['KeyH', qKeys.H],
  ['KeyI', qKeys.I],
  ['KeyJ', qKeys.J],
  ['KeyK', qKeys.K],
  ['KeyL', qKeys.L],
  ['KeyM', qKeys.M],
  ['KeyN', qKeys.N],
  ['KeyO', qKeys.O],
  ['KeyP', qKeys.P],
  ['KeyQ', qKeys.Q],
  ['KeyR', qKeys.R],
  ['KeyS', qKeys.S],
  ['KeyT', qKeys.T],
  ['KeyU', qKeys.U],
  ['KeyV', qKeys.V],
  ['KeyW', qKeys.W],
  ['KeyX', qKeys.X],
  ['KeyY', qKeys.Y],
  ['KeyZ', qKeys.Z],
  ['Numpad0', qKeys.Numpad0],
  ['Numpad1', qKeys.Numpad1],
  ['Numpad2', qKeys.Numpad2],
  ['Numpad3', qKeys.Numpad3],
  ['Numpad4', qKeys.Numpad4],
  ['Numpad5', qKeys.Numpad5],
  ['Numpad6', qKeys.Numpad6],
  ['Numpad7', qKeys.Numpad7],
  ['Numpad8', qKeys.Numpad8],
  ['Numpad9', qKeys.Numpad9],
  ['NumpadMultiply', qKeys.NumpadMultiply],
  ['NumpadAdd', qKeys.NumpadAdd],
  ['NumpadSubtract', qKeys.NumpadSubtract],
  ['NumpadDecimal', qKeys.NumpadDecimal],
  ['NumpadDivide', qKeys.NumpadDivide],
  ['F1', qKeys.F1],
  ['F2', qKeys.F2],
  ['F3', qKeys.F3],
  ['F4', qKeys.F4],
  ['F5', qKeys.F5],
  ['F6', qKeys.F6],
  ['F7', qKeys.F7],
  ['F8', qKeys.F8],
  ['F9', qKeys.F9],
  ['F10', qKeys.F10],
  ['F11', qKeys.F11],
  ['F12', qKeys.F12],
  ['F13', qKeys.F13],
  ['F14', qKeys.F14],
  ['F15', qKeys.F15],
  ['F16', qKeys.F16],
  ['F17', qKeys.F17],
  ['F18', qKeys.F18],
  ['F19', qKeys.F19],
  ['F20', qKeys.F20],
  ['F21', qKeys.F21],
  ['F22', qKeys.F22],
  ['F23', qKeys.F23],
  ['F24', qKeys.F24],
  ['Semicolon', qKeys.Semicolon],
  ['Equal', qKeys.Equal],
  ['Comma', qKeys.Comma],
  ['Minus', qKeys.Minus],
  ['Period', qKeys.Period],
  ['Slash', qKeys.Slash],
  ['Backquote', qKeys.Backquote],
  ['BracketLeft', qKeys.BracketLeft],
  ['Backslash', qKeys.Backslash],
  ['BracketRight', qKeys.BracketRight],
  ['Quote', qKeys.Quote],
  ['ControlLeft', qKeys.Ctrl],
  ['ControlRight', qKeys.CtrlRight],
  ['AltLeft', qKeys.Alt],
  ['AltRight', qKeys.AltRight],
  ['ShiftLeft', qKeys.Shift],
  ['ShiftRight', qKeys.ShiftRight],
  ['MetaLeft', qKeys.Meta],
  ['MetaRight', qKeys.MetaRight],
  ['NumLock', qKeys.NumLock],
  ['ScrollLock', qKeys.ScrollLock],
  ['PrintScreen', qKeys.PrintScreen],
  ['Pause', qKeys.Pause],
]);

const MOUSE_BUTTON_TO_UIOHOOK = new Map<number, number>([
  [0, qKeys.MouseButton1],
  [1, qKeys.MouseButton3],
  [2, qKeys.MouseButton2],
  [3, qKeys.MouseButton4],
  [4, qKeys.MouseButton5],
]);

/** Maps a DOM keyboard or mouse event to uiohook key codes, including held modifiers. */
export const collectUiohookCodes = (event: KeyboardEvent | MouseEvent): number[] => {
  const codes = new Set<number>();

  if (event.ctrlKey) codes.add(qKeys.Ctrl);
  if (event.shiftKey) codes.add(qKeys.Shift);
  if (event.altKey) codes.add(qKeys.Alt);
  if (event.metaKey) codes.add(qKeys.Meta);

  if (event instanceof KeyboardEvent) {
    const keyCode = DOM_CODE_TO_UIOHOOK.get(event.code);
    if (keyCode !== undefined) codes.add(keyCode);
  } else {
    const buttonCode = MOUSE_BUTTON_TO_UIOHOOK.get(event.button);
    if (buttonCode !== undefined) codes.add(buttonCode);
  }

  return [...codes];
};
